services:
  migrations:
    image: payments-api-migrations
    container_name: payments-api-migrations
    build:
      context: .
      dockerfile: migrations/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    networks:
      - apps

  seeds:
    image: payments-api-seeds
    container_name: payments-api-seeds
    build:
      context: .
      dockerfile: seeds/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    networks:
      - apps
    depends_on:
      migrations:
        condition: service_completed_successfully

  payments-api:
    hostname: payments-api
    container_name: payments-api
    image: payments-api
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - KAFKA_BROKERS=kafka:29092
    ports:
      - "6001:6000"
    networks:
      - apps
    depends_on:
      migrations:
        condition: service_completed_successfully
      seeds:
        condition: service_completed_successfully

networks:
  apps:
    external: true
