# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test PR

on:
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "synchronize", "reopened" ]

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Generate
      run: make generate

    - name: Build
      run: make build

    - name: Test
      run: make test.cover
